load_module modules/ngx_http_modsecurity_module.so;

worker_processes auto;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format custom_format '$remote_addr - $remote_user [$time_local] $scheme://$host '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent" '
                             'rt="$request_time" uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

    # DNS nội bộ của Docker (Bắt buộc phải có để giải quyết hostname trong biến)
    resolver 127.0.0.11 valid=30s;
    resolver_timeout 5s;

    server {
        listen 80;
        server_name team2.saigonnewport.local;

        access_log /var/log/nginx/access.log custom_format;
        access_log /dev/stdout custom_format; # Thêm dòng này để đẩy ra cả Docker logs
        error_log /var/log/nginx/error.log warn;
        error_log /dev/stderr; # Thêm dòng này để đẩy lỗi ra Docker logs

        modsecurity on;
        modsecurity_rules_file /etc/nginx/modsecurity/modsecurity.conf;
        
        location / {
            #proxy_pass http://host.docker.internal:200;
            proxy_pass http://172.16.100.144:200;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}